@startuml
class worldofzuul.Game {
~ Parser parser
~ Room currentRoom
~ TrashCanRoom garbageArea
~ RegularRoom outside
~ PlayerScore playerScore
~ Inventory playerInventory
~ void createRooms()
+ void play()
~ void printWelcome()
~ boolean processCommand(Command)
~ void printHelp()
~ void goRoom(Command)
~ boolean quit(Command)
~ void pickup(Command)
~ void throwout(Command)
~ void trashDescription(Command)
~ void printPlayerInventory(Inventory)
+ {static} void main(String[])
}
@enduml