@startuml
enum worldofzuul.Trashtype {
- String trashString
+ Sprites sprite
+ String filepath
+ String getFilepath()
+ String toString()
-- trashString--
FOOD_WASTE("food", "worldofzuul/img/TrashSprites/BittenApple.png"),

    METAL_AND_GLASS("Metal", "worldofzuul/img/TrashSprites/Can.png"),

    PAPER("paper", "worldofzuul/img/TrashSprites/CrumbledPaper.png"),

    PLASTIC("plastic", "worldofzuul/img/TrashSprites/BottleofWater.png"),

    RESIDUAL_WASTE("residual", "worldofzuul/img/TrashSprites/TrashBag.png");
}
@enduml